import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/tech-school.png";
import web2 from "../public/Colegio.png";
import web3 from "../public/space turism.jpg";
import web4 from "../public/tesla ui.png";
import web5 from "../public/irpf.png";
import web6 from "../public/taskify.png";
import Link from "next/link";
import { useRouter } from "next/router";
import br from '../locales/pt-BR/home'
import usa from '../locales/en/home'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const router = useRouter()
  const {locale} = router
  const t = locale === 'en-US' ? usa : br;

  const changeLanguage = (e) => {
    const locale = e.target.value;
    router.push(router.pathname, router.asPath, { locale });
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Roberto´s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between items-center dark:text-white">
            <h1 className="font-burtons text-xl">Roberto´s Portfolio</h1>
            <div className="flex flex-wrap justify-center">
            <ul className="flex items-center w-28 justify-between  ">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl"
              />
            </li>
            <li>
            <select
            onChange={changeLanguage}
            defaultValue={locale}
            className="text-black outline-none text-shadow-sm text-lg bg-transparent tracking-wide dark:text-white"
          >
            <option className="text-black" value="pt-br">PT-BR</option>
            <option className="text-black" value="en-US">EN-US</option>
          </select>
            </li>
          </ul>
          <a
          className=" w-44 bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
          href="cvs.rar"
          download="cvs.rar" 
        >
          {t.DownloadCv}
        </a>
            </div>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Roberto Athos
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front End Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                {t.Frase}
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3">
              <Link href="https://github.com/RobertoAthos"><AiFillGithub className="text-gray-600 hover:text-blue-500 cursor-pointer dark:text-gray-400 dark:hover:text-blue-500" /></Link>
              <Link href="https://www.linkedin.com/in/roberto-athos/"><AiFillLinkedin className="text-gray-600 hover:text-blue-500 cursor-pointer dark:text-gray-400 dark:hover:text-blue-500"  /></Link>
            </div>
            
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">{t.Sobre}</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                {t.SobreDescrição}
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Ui/Ux
              </h3>
              <p className="py-2">
              {t.SkillsDescription1}
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Adobe Xd</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Front-End
              </h3>
              <p className="py-2">
             {t.SkillsDescription2}
              </p>
              <h4 className="py-4 text-teal-600">Stacks</h4>
              <p className="text-gray-800 py-1">Html</p>
              <p className="text-gray-800 py-1">Css</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">Reactjs</p>
              <p className="text-gray-800 py-1">Nextjs</p>
              <p className="text-gray-800 py-1">Typescript</p>
              <p className="text-gray-800 py-1">Redux</p>
              <p className="text-gray-800 py-1">Style-Components</p>
              <p className="text-gray-800 py-1">GraphQl</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Back-End</h3>
              <p className="py-2">
              {t.SkillsDescription3}
              </p>
              <h4 className="py-4 text-teal-600">Stacks</h4>
              <p className="text-gray-800 py-1">NodeJS express</p>
              <p className="text-gray-800 py-1">Jwt Authentication</p>
              <p className="text-gray-800 py-1">Firebase</p>
              <h4 className="py-4 text-teal-600">Database:</h4>
              <p className="text-gray-800 py-1">Mongo DB</p>
              <p className="text-gray-800 py-1">PostgresSQL</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            {t.PortfolioDescription}
            </p>
          
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg ">
              <Image
                className=" rounded-t-2xl object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">{t.ProjectTitle1}</span>
                <p className="mt-4 mb-4">{t.ProjectDescription1}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/tech-school-system'><a className="underline mb-2 hover:text-blue-500">Github</a></Link>
                <Link href='https://tech-school-client-oi0mlg1pu-robertoathos.vercel.app/'><a className="underline mb-2 hover:text-blue-500"> Url site</a></Link>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg">
              <Image
                className="rounded-lg object-cover shadow-sm"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">Colégio Batista Landing Page</span>
                <p className="mt-4 mb-4">{t.ProjectDescription2}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/ColegioBatistaSite'><a className="underline mb-2 hover:text-blue-500"> Github</a></Link>
                <Link href='https://robertoathos.github.io/ColegioBatistaSite/'><a className="underline mb-2 hover:text-blue-500">Url site</a></Link>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg">
              <Image
                className="rounded-lg object-cover shadow-sm"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">Space Tourism</span>
                <p className="mt-4 mb-4">{t.ProjectDescription3}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/space-tourism'><a className="underline mb-2 hover:text-blue-500"> Github</a></Link>
                <Link href='https://spacetourism-web.vercel.app/'><a className="underline mb-2 hover:text-blue-500">Url site</a></Link>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg">
              <Image
                className="rounded-lg object-cover shadow-sm"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">Tesla Ui Clone</span>
                <p className="mt-4 mb-4">{t.ProjectDescription4}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/tesla-ui-clone'><a className="underline mb-2 hover:text-blue-500">Github</a></Link>
                <Link href='https://teslaui.vercel.app/'><a className="underline mb-2 hover:text-blue-500">Url site</a></Link>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg">
              <Image
                className="rounded-lg object-cover shadow-sm"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">{t.ProjectTitle2}</span>
                <p className="mt-4 mb-4">{t.ProjectDescription5}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/Relayout-Imposto-de-Renda'><a className="underline mb-2 hover:text-blue-500"> Github</a></Link>
                <Link href='https://imposto-de-renda-client-6ylr8c93n-robertoathos.vercel.app/'><a className="underline mb-2 hover:text-blue-500">Url site</a></Link>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 bg-slate-50 rounded-2xl shadow-lg">
              <Image
                className="rounded-lg object-cover shadow-sm"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
              <div className="p-4">
                <span className="text-xl text-cyan-500">Taskify, GPT-3 App</span>
                <p className="mt-4 mb-4">{t.ProjectDescription6}</p>
                <div className="flex flex-col">
                <Link href='https://github.com/RobertoAthos/AiSolve-GPT3'><a className="underline mb-2 hover:text-blue-500"> Github</a></Link>
                <Link href='https://taskifyai.vercel.app/'><a className="underline mb-2 hover:text-blue-500">Url site</a></Link>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full flex justify-center"><button className="bg-blue-500 text-white p-6 rounded-md hover:bg-blue-700"><Link href='https://github.com/RobertoAthos?tab=repositories'><a>{t.VerMaisBtn}</a></Link></button></div>
        </section>
      </main>
    </div>
  );
}
